<?php
/**
 * Страница "Содержание".
 * 
 * Английская (британская) локализация.
 *
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Sitemap</h1>
    <div class="g-help-icon">
        <img src="<?= $assetsUrl, '/images/icon.svg' ?>" />
    </div>
    <p>Creating an XML file with information for search engines about website pages that are subject to indexing. A Sitemaps can help search engines determine the location of pages on a site, when they were last updated, how often they were updated, and their importance relative to other pages on the site so that the search engine can index the site more intelligently.</p>

    <h2>Contents:</h2>
    <ul class="g-help-list">
        <li><a href="<?= $url('settings') ?>">Module settings</a></li>
    </ul>
</article>