<?php
/**
 * Страница "Настройка модуля".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Настройка модуля "Карта сайта"</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/settings.png' ?>" />
    </div>
    <p>Форму настроек модуля можно вызвать из <a href="<?= $url('index', 'extension:gm.be.config.desk') ?>">Панели конфигурации</a> или из <a href="<?= $url('index', 
    'extension:gm.be.mp.mmanager') ?>">Менеджера модулей</a>.</p>
    <h2>Поля формы</h2>
    <ul class="g-help-list">
        <li><b>Записей URL-адресов в файле.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</li>
    </ul>
</article>