<?php
/**
 * Страница "Настройка модуля".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Customizing module "Sitemap"</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/settings.png' ?>" />
    </div>
    <p>The module settings form can be called from <a href="<?= $url('index', 'extension:gm.be.config.desk') ?>">Configuration panel</a> or from <a href="<?= $url('index', 'extension:gm.be.mp.mmanager') ?>">Module manager</a>.</p>
    <h2>Form fields</h2>
    <ul class="g-help-list">
        <li><b>URL entries in the file.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</li>
    </ul>
</article>